// SPDX-License-Identifier: GPL-3.0-only
(()=>{
'use strict';
const $=id=>document.getElementById(id),C=EngineeringCore,E=DogModelEngine,M=MODEL.metadata;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const help={
 scope:['This model’s scope','Task-trained model','This is a genuine five-block neural network trained to recover a dog’s name from short example conversations. It knows 24 name tokens and a small set of sentence patterns.','48,352 learned scalar parameters, 55 vocabulary entries, and 64 sequence positions. All name tokens appeared in training.','You can change context and decoding settings. New names and unfamiliar wording can fail. This model is not a benchmark of general language ability.'],
 context:['Context window','Input · 64 positions','Context is the information supplied to the current model run. It includes the earlier facts, the question, and special boundary tokens.','The default prompt takes 22 positions. Input positions plus the maximum requested new tokens must fit within 64.','Removing the dog fact removes evidence from the input. The trained model can then predict its learned “unknown” token. No weights are updated.'],
 inference:['Inference settings','Adjustable at run time','Inference means using already-trained weights to produce a prediction. Decoding controls choose among the scores produced by the network.','These controls change probability processing, token selection, stopping, or computation reuse.','Changing them does not retrain the network, expand its vocabulary, or add context that was not supplied.'],
 mode:['Greedy or sampling?','Token-selection rule','Greedy decoding picks the token with the highest model score. Sampling draws a token according to the processed probability distribution.','At the default input, greedy chooses Milo. Sampling can choose a different token, especially with a higher temperature.','Temperature and filters change the displayed distribution. With greedy selection, the best-scoring token remains the choice.'],
 temperature:['Temperature','Adjustable · 0 to 2 · default 1','Temperature divides the logits before softmax. Lower values concentrate probability around the best-scoring token. Higher values spread probability across alternatives.','At 1, scores use ordinary softmax. At 0, this implementation uses the highest-scoring token. At 2, lower-scoring candidates become more likely.','The network’s logits stay fixed. Sampling probabilities change. Temperature does not improve the model’s knowledge or accuracy.'],
 topK:['Top-k','Adjustable · 0 to 55 · 0 means off','Keep only the k most probable candidates after temperature, set the others to zero, and renormalize.','With k = 3, at most three vocabulary tokens remain available. With k = 1, only the best candidate remains.','The candidate set changes, not the learned scores. Top-p is applied after this top-k filter in this demo.'],
 topP:['Top-p · nucleus sampling','Adjustable · 0.05 to 1 · default 1','Sort candidates by probability and keep the smallest prefix whose cumulative probability reaches p. Include the candidate that crosses the threshold.','At p = 0.90, a single token already above 90% is enough. A flatter distribution may require several tokens.','The number of eligible tokens adapts to the current distribution. Kept probabilities are renormalized before sampling.'],
 maxTokens:['Max new tokens','Adjustable · 1 to 8 · default 4','This is an upper limit on how many output tokens may be selected. The model can finish earlier by predicting its stop token.','This task usually produces Milo followed by <eos>. Set the limit to 1 and the run ends after the name because the limit was reached.','Changes the generation budget and stop reason. It does not change the score of the first predicted token.'],
 seed:['Random seed','Adjustable · unsigned 32-bit integer','A seed initializes the pseudorandom number generator used for sampling. It makes a draw sequence reproducible within this implementation.','The same context, weights, settings, and seed produce the same sampled sequence. The demo uses a simple deterministic LCG.','Different seeds may choose different candidates. A seed has no effect on greedy selection or neural-network logits.'],
 cache:['Reuse the KV cache','Computation setting · enabled by default','Every attention layer computes key and value vectors for token positions. Keeping previous vectors avoids recomputing them for the next output token.','Enabled: prefill 22 positions, then process the one newly generated name. Disabled: prefill 22, then recompute the 23-position prefix.','Output scores should match. The number of evaluated positions changes. Small measured timings can fluctuate; compute work is the clearer comparison here.'],
 probabilities:['Logits and probabilities','Measured model output','Logits are unconstrained numerical scores from the vocabulary head. Softmax converts them into a distribution that sums to 1.','The chart starts with all 55 vocabulary scores, then applies temperature, top-k, and top-p. Grey bars show candidates excluded by the filters.','These are model probabilities under this decoding rule, not a calibrated promise that an answer is correct.'],
 tokenizer:['Tokenization','Fixed vocabulary · 55 entries','The tokenizer splits English words, apostrophes, punctuation, and special tokens. It maps each piece to a vocabulary ID.','“dog’s” becomes dog, apostrophe, s after normalizing the apostrophe. <bos> starts the sequence; <answer> marks where to predict the name.','Unknown pieces map to <unk>. Production tokenizers often use subword pieces; this teaching model has a much smaller tokenizer.'],
 readout:['Intermediate vocabulary readouts','Diagnostic view · temperature 1','Apply the shared final normalization and vocabulary head to the answer-boundary vector after each block. This reveals how that readout changes across layers.','Only the readout after block 5 is the trained final prediction. Earlier layers were not trained to make independent calibrated predictions.','Selecting a layer changes the inspection view, not the model’s architecture or output. These rows use unfiltered softmax at temperature 1.'],
 attention:['Attention weights','Measured computation','A query is compared with available keys. Softmax turns the scaled similarity scores into weights used to mix value vectors.','Each block has four heads. The answer-boundary query can attend to the dog name, distractors, punctuation, and other available positions.','Different heads use different learned projections. Attention alone is not a complete explanation of the final answer.'],
 qkv:['Queries, keys, and values','Learned projections','Queries and keys produce similarity scores. Values carry the vectors that get mixed according to the attention weights.','A 32-dimensional hidden vector is projected into Q, K, and V, each 32-dimensional. Each is split into four heads of eight dimensions.','The trained projection matrices determine all of these values. Each transformer block uses its own matrices.'],
 normalization:['Layer normalization','Fixed operation + learned scale and bias','For each token, subtract the mean across its hidden dimensions and divide by the standard deviation. Then apply a learned scale and offset.','The stability constant epsilon is 0.00001. It is added to the variance before the square root.','Keeps the numerical scale manageable. The learned scale and bias remain fixed during inference.'],
 prefill:['Prefill','Measured computation phase','Process the input sequence through every transformer block and build the key/value cache for its positions.','The timer measures the actual JavaScript prefill in this device or server. The first next-token distribution comes from this pass.','Longer input usually requires more work. The displayed time is a local observation, not a production performance benchmark.'],
 decode:['Decode','Measured generation phase','Select a new token, run the model on the extended sequence, and repeat until an end token or limit is reached.','The name is selected first. Processing that name predicts the next token, usually <eos>.','Generation is sequential in this implementation. Cache reuse avoids repeating earlier key/value projections.'],
 compute:['Compute work','Counted block-position evaluations','Count each token position evaluated in each of the five blocks, including recomputation when caching is disabled.','For 22 input positions and one additional processed name, 23 × 5 = 115 block-position evaluations.','This is a reproducible work counter, not FLOPs. It makes cache savings visible without relying on noisy milliseconds.'],
 memory:['Model memory','Weights, context, cache, and activations','Weights contain learned patterns. Context supplies this request’s facts. KV caches and activations are temporary numerical state used for computation.','The cache stores 5 × positions × 2 × 32 numbers. Additional attention traces and JavaScript object overhead are not included in that scalar count.','A new run gets fresh request state. Saved long-term memory would require an external app or data store, which this demo does not have.'],
 outputHead:['Vocabulary output head','Learned matrix · 55 × 32','After final normalization, multiply the 32-number answer-boundary vector by a learned matrix to produce one logit for every vocabulary entry.','The head has 1,760 learned weights and no bias. The full vocabulary includes names, ordinary words, and special tokens.','This is where the network’s final vector becomes next-token scores. Sampling and filtering happen after this projection.'],
 mlp:['Feed-forward network · MLP','Learned transformation · 32 → 64 → 32','Expand the vector, apply the nonlinear GELU function, then project it back to the hidden width. This operates separately at each token position.','Each block’s MLP uses its own matrices and biases. Its output is added to the residual stream.','The MLP contributes to the prediction along with attention; it is not a separate memory database.'],
 residual:['Residual connection','Fixed addition','Add the result of a transformation back to the vector that entered it. This creates a path for information through the stack.','One residual addition follows attention; another follows the MLP in each block.','Adds no learned parameters itself. It preserves a direct route while each block learns a change to the representation.'],
 layers:['Transformer blocks','Architecture · fixed at 5','A block contains causal attention, an MLP, normalization, and residual additions. The model applies five blocks in sequence.','These five blocks have different learned weights but the same structure. They are not manually assigned skills such as “grammar” or “reasoning.”','Changing the number of blocks would create a different architecture and require training compatible weights.'],
 width:['Hidden width','Architecture · 32 dimensions','Each token position is represented by 32 numbers throughout the residual stream. These dimensions are learned features, not individually named concepts.','Attention and the MLP read and modify these vectors. The output head turns the final vector into vocabulary scores.','A different width changes tensor shapes and parameter count. It cannot be changed with an inference slider.'],
 heads:['Attention heads','Architecture · 4 per block','Split the Q, K, and V projections into four groups so the block can form different attention distributions.','32 hidden dimensions ÷ 4 heads = 8 dimensions per head. Inspecting a head changes only the display.','Changing the number of heads is an architecture change. This checkpoint is trained with four.'],
 headWidth:['Head dimension','Architecture · 8','Each attention head uses eight dimensions for its queries, keys, and values. Dot products are scaled by the square root of eight.','The score is dot(Q, K) / √8 before softmax. Scaling helps control score magnitude.','It is derived from hidden width divided by head count. It is not an adjustable decoding setting.'],
 ffWidth:['MLP intermediate width','Architecture · 64','The first MLP projection expands from 32 to 64 dimensions. GELU is applied before projecting back to 32.','fc1 has shape 64 × 32; fc2 has shape 32 × 64. Both have learned biases.','Changes the size and capacity of the MLP. New dimensions would require a new checkpoint.'],
 parameterCount:['Learned parameter count','Architecture · 48,352 scalars','Add the number of scalar entries across all embedding, projection, normalization, and bias tensors.','There are 65 tensors. The tensor explorer exposes every row, column, and value. KV cache entries are not learned parameters.','These values change during training. The deployed model treats them as read-only.'],
 position:['Position embeddings','Architecture · learned · 64 × 32','Each position has a learned 32-number vector, added to its token embedding before block 1.','Positions 0 through 63 are supported. This model does not use rotary position embeddings.','Position information lets the network distinguish sequence order. Extending the table would require training those added positions.'],
 epsilon:['Normalization epsilon','Architecture constant · 1e-5','A small positive number is added to the variance during layer normalization to avoid division by zero and stabilize small variances.','The browser and PyTorch use epsilon = 0.00001 for every normalization.','This is part of the model’s numerical definition. Changing it can change logits and break checkpoint parity.'],
 precision:['Numerical precision','Implementation detail','Training uses PyTorch float32 tensors. JavaScript computes with double-precision Number values. Bundled weights are rounded to eight decimal places.','Browser logits were compared with the PyTorch reference and agreed within 0.0001 per logit.','Precision affects storage, memory use, and small numerical differences. This demo does not simulate quantization.'],
 batch:['Training batch size','Training setting · 96 examples','The optimizer averages learning signals from a batch of examples before making an update.','This run sampled 96 training examples for each of 900 optimizer steps.','Changing batch size affects training dynamics and memory use. It is unrelated to how many words the model generates.'],
 steps:['Optimizer steps','Training setting · 900','An optimizer step updates the learned parameters using the gradients from one batch.','900 steps × 96 sampled examples = 86,400 training-example presentations, drawn with replacement from 12,000 unique prompts.','More steps mean more updates, not necessarily better generalization. The chart shows the recorded batch loss.'],
 learningRate:['Learning rate','Training schedule · 0.003 → 0.0003','The learning rate controls the scale of each optimizer update. This run gradually reduced it with a cosine schedule.','lr = 0.0003 + 0.0027 × (1 + cos(π × step / 900)) / 2.','Affects learning, not inference. Too large can destabilize training; too small can slow it down.'],
 optimizer:['AdamW optimizer','Training algorithm','AdamW adapts update sizes using running estimates of gradients and their squared values, with decoupled weight decay.','The training script uses torch.optim.AdamW with its default beta values 0.9 and 0.999, epsilon 1e-8, and weight decay 0.01.','These values govern parameter updates. They do not run when a user requests a prediction.'],
 weightDecay:['Weight decay','Training setting · 0.01','AdamW applies a decay term that tends to shrink parameter magnitudes during training.','The coefficient is 0.01 in the original training script.','It is a training regularizer. It does not reduce the KV cache or erase facts during inference.'],
 clip:['Gradient clipping','Training setting · norm cap 1.0','If the total gradient norm is too large, rescale the gradients before the optimizer update.','The training script calls clip_grad_norm_ with a maximum norm of 1.0.','Limits unusually large training updates. It does not clip attention probabilities or output tokens.'],
 trainingSeed:['Training seed','Training setting · 20260915','The training run uses fixed seeds for initialization and synthetic-data sampling so it can be reproduced in a compatible environment.','This seed is separate from the inference sampling seed in the Playground.','It affects the learned checkpoint. Changing it requires training a new model, rather than rerunning inference.'],
 loss:['Cross-entropy loss','Training objective','Cross entropy penalizes low probability assigned to the correct next token. The average here covers the answer name and the following <eos> token.','Most context-token targets are masked out of the training objective. This is task-specific next-token training.','Lower training loss means the target tokens receive more probability on those batches. It is not a guarantee about unseen inputs.'],
 evaluation:['Held-out evaluation','Measured synthetic-task result','Training and test prompt strings were split deterministically by a SHA-256 hash. Test prompts were not used as training examples.','All 1,200 held-out prompts were answered correctly. All 24 name tokens were present in the training vocabulary and examples.','This checks similar synthetic patterns. It does not establish performance on unfamiliar names, broad language tasks, or adversarial inputs.'],
 api:['Prediction API','Live endpoint · POST /api/predict','The server validates JSON input, tokenizes the context, runs the trained model, and returns generated tokens, probabilities, timings, and usage.','Browser and server share the same inference code and checkpoint. A fresh model instance isolates each request’s context and cache.','The request crosses a network boundary. The returned timing measures server computation; the UI also measures the full round trip.'],
 deploymentMemory:['Memory ownership','Deployment boundary','Model weights can be reused across requests. Each request’s context and cache must remain isolated. Durable memory requires a separate storage system.','The Worker bundles weights once and creates a model instance for each API call. This demo has no database, analytics, or prompt logging.','A production service can introduce retrieval or persistent sessions explicitly; they are not automatic properties of an LLM.'],
 release:['Deployment lifecycle','Build → validate → release','Train and evaluate the model, freeze its checkpoint, bundle the inference runtime, and publish the exact validated application version.','This project produces a self-contained HTML page and a Worker-compatible JavaScript server. Sites hosts the public release.','Deployment changes which code and checkpoint are served. It does not train the model or alter its weights.']
};
let result=null,selectedLayer=4,operation='normalize',traceStage=6,playing=false,traceTimer=null,activeView='studio',tensorName='token_embedding.weight',tensorStart=0,stackMode='browser',stackSelected='runtime',apiBusy=false;
const readSettings=()=>({temperature:Number($('temperature').value),topK:Number($('top-k').value),topP:Number($('top-p').value),maxTokens:Number($('max-tokens').value),seed:Number($('seed').value),mode:$('mode').value,useCache:$('cache-toggle').checked});
function currentRequest(){return{context:$('context').value,settings:readSettings()};}
function stopTrace(){playing=false;clearTimeout(traceTimer);$('play-trace').textContent='▶ Play trace';}
function compute(){stopTrace();try{result=C.generate(MODEL,currentRequest());selectedLayer=4;traceStage=6;const unknown=result.trace.tokens.filter(t=>!M.vocab.includes(t));$('input-status').className='input-status';$('input-status').textContent=result.usage.inputTokens+' input tokens'+(unknown.length?' · unfamiliar pieces → <unk>: '+[...new Set(unknown)].join(', '):' · recognized vocabulary');$('run').disabled=false;renderAll();}catch(e){result=null;$('input-status').className='input-status error';$('input-status').textContent=e.message;$('answer').textContent='Check the input';$('answer-probability').textContent='—';$('answer-tokens').textContent='No prediction was run.';$('play-trace').disabled=true;$('step-trace').disabled=true;for(const id of ['token-strip','layer-stack','candidate-bars','attention-bars','block-flow','vector-a','vector-b','score-table'])$(id).replaceChildren();for(const id of ['prefill-time','decode-time','compute-work','cached-positions','kv-scalars'])$(id).textContent='—';$('trace-note').textContent='Correct the input to compute a new trace.';$('candidate-note').textContent='No current distribution.';$('operation-title').textContent='No current forward pass';$('operation-description').textContent=e.message;$('operation-formula').textContent='—';$('attention-detail').textContent='Correct the input in Playground to inspect its attention.';renderSettings();renderDeployment();}}
function renderAll(){renderSettings();renderPlayground();populateInspection();renderInternals();renderTensor();renderTraining();renderDeployment();}
function renderSettings(){const s=readSettings();$('temperature-value').textContent=s.temperature.toFixed(2);$('top-k-value').textContent=s.topK||'Off';$('top-p-value').textContent=s.topP.toFixed(2);$('settings-note').textContent=s.mode==='greedy'?'Greedy always selects the best-scoring token. Switch to sampling to see temperature and seed change the draw.':'Sampling uses the filtered distribution and your seed. Reusing the same inputs and seed reproduces the draw.';}
function renderPlayground(){if(!result)return;const trace=result.trace,head=$('play-head').value,c=trace.cache[selectedLayer],q=trace.ids.length-1;const a=head==='mean'?c.attention[q][0].map((_,i)=>c.attention[q].reduce((s,h)=>s+h[i],0)/4):c.attention[q][Number(head)];
 $('token-budget').textContent=trace.ids.length+' / 64 positions ⓘ';$('token-strip').innerHTML=trace.tokens.map((t,i)=>'<span class="token-unit '+(t==='<answer>'?'boundary':a[i]>.15?'key-token':'')+'" title="Position '+i+' · attention '+(a[i]*100).toFixed(2)+'%">'+escape(t)+'</span>').join('');
 $('layer-stack').innerHTML=trace.readouts.map((logits,l)=>{const p=E.softmax(logits),id=p.indexOf(Math.max(...p)),vector=trace.cache[l].hidden[q];return'<button class="layer-card '+(selectedLayer===l?'selected ':'')+(playing&&traceStage<l+1?'future':'')+'" data-layer="'+l+'" aria-pressed="'+(selectedLayer===l)+'"><span class="layer-title"><span>0'+(l+1)+'</span>Block '+(l+1)+'</span><span class="neurons" aria-label="32 hidden dimensions">'+vector.map(v=>'<i style="opacity:'+(.18+.82*Math.min(1,Math.abs(v)/2))+'"></i>').join('')+'</span><span class="readout"><strong>'+escape(M.vocab[id])+'</strong><small>'+(p[id]*100).toFixed(1)+'% · '+(l===4?'final':'intermediate')+'</small></span></button>'}).join('');
 const notes=['<strong>Embeddings.</strong> Token IDs select learned vectors; learned position vectors are added. This trace replays the measured forward pass.','<strong>Block 1.</strong> Four attention heads mix available value vectors. Its MLP transforms the result.','<strong>Block 2.</strong> New projections act on contextual vectors from the first block. Each block has its own parameters.','<strong>Block 3.</strong> The shared output-head readout reveals one view of the changing representation. It is diagnostic at this layer.','<strong>Block 4.</strong> Attention, the MLP, and residual paths all contribute. The model’s input context remains the same.','<strong>Block 5.</strong> This block’s final answer-boundary vector is normalized and projected into the vocabulary.','<strong>Prediction ready.</strong> All numbers come from the trained model. Select a block, change a setting, or open the internals.'];$('trace-note').innerHTML=notes[traceStage];$('trace-status').textContent=playing?'TRACE REPLAY':'LIVE VALUES';$('play-trace').disabled=false;$('step-trace').disabled=false;
 $('answer').textContent=result.text||'<eos>';$('answer-mode').textContent=result.settings.mode.toUpperCase();$('answer-probability').textContent=(result.generated[0].probability*100).toFixed(2)+'%';$('answer-tokens').textContent=result.generated.map(x=>x.token).join(' → ')+' · stop: '+result.stop;$('prefill-time').textContent=result.timings.prefillMs.toFixed(2)+' ms';$('decode-time').textContent=result.timings.decodeMs.toFixed(2)+' ms';$('compute-work').textContent=result.usage.layerPositionEvaluations+' positions';
 const p=result.probabilities,rank=p.temperature.map((v,id)=>({id,prob:p.final[id],base:v})).sort((a,b)=>b.prob-a.prob||b.base-a.base).slice(0,5);$('candidate-bars').innerHTML=rank.map(x=>'<div class="candidate-row '+(!x.prob?'filtered':'')+'"><span>'+escape(M.vocab[x.id])+'</span><div class="candidate-track"><div class="candidate-fill" style="width:'+(x.prob||x.base)*100+'%"></div></div><span class="percent">'+(x.prob?(x.prob*100).toFixed(2)+'%':'out')+'</span></div>').join('');$('candidate-note').textContent=p.kept.length+' of 55 candidates retained. Chart shows the top 5; other retained mass: '+((1-rank.reduce((s,x)=>s+x.prob,0))*100).toFixed(2)+'%.';
 $('attention-bars').innerHTML=a.map((v,i)=>({v,i})).sort((x,y)=>y.v-x.v).slice(0,4).map(x=>'<div class="candidate-row"><span>'+escape(trace.tokens[x.i])+'</span><div class="candidate-track"><div class="candidate-fill" style="width:'+x.v*100+'%"></div></div><span class="percent">'+(x.v*100).toFixed(1)+'%</span></div>').join('');$('selected-layer').textContent=selectedLayer+1;$('cached-positions').textContent=result.usage.cachePositions;$('kv-scalars').textContent=result.usage.cacheNumbers.toLocaleString();}
function tickTrace(){if(!playing)return;traceTimer=setTimeout(()=>{traceStage++;selectedLayer=Math.min(4,Math.max(0,traceStage-1));if(traceStage>=6)stopTrace();renderPlayground();if(playing)tickTrace()},950);}
function playTrace(){if(playing){stopTrace();renderPlayground();return;}if(!result)return;playing=true;traceStage=0;selectedLayer=0;$('play-trace').textContent='Ⅱ Pause trace';renderPlayground();tickTrace();}
const operations={normalize:['Normalize','32 → 32','Normalize the incoming vector','Center and rescale each token’s hidden dimensions, then apply learned scale and bias.','LN(x) = (x − mean) / √(variance + ε) × scale + bias','input','normalized','normalization'],qkv:['Project Q, K, V','32 → 96','Create queries, keys, and values','A learned projection creates 96 values. They split into Q, K, and V, then four attention heads.','Q, K, V = split(Wqkv × LN(x) + bqkv)','normalized','qkv','qkv'],attention:['Mix values','4 heads × 8','Use attention to mix available values','Each head compares its query with earlier keys, applies softmax, and mixes values. The four head outputs are concatenated.','attention = softmax(QKᵀ / √8 + causal mask) × V','query','mixed','attention'],residual:['Project + add','32 → 32','Return to the residual stream','A learned projection mixes the head outputs. Add that result to the block’s incoming vector.','r = x + Wo × attention_output + bo','mixed','residual','residual'],mlp:['Normalize + MLP','32 → 64','Expand and apply GELU','The second normalization feeds a learned expansion. GELU transforms these values before the final MLP projection.','hidden_mlp = GELU(W1 × LN(r) + b1)','normalized2','activated','mlp'],output:['Project + add','64 → 32','Produce the block’s output','The MLP projects back to 32 dimensions. Its output is added to the residual stream and becomes the next block’s input.','block_output = r + W2 × hidden_mlp + b2','residual','output','residual']};
function populateInspection(){if(!result)return;const oldLayer=$('inspect-layer').value||'4',oldQuery=$('inspect-query').value; $('inspect-layer').innerHTML=Array.from({length:5},(_,i)=>'<option value="'+i+'">Block '+(i+1)+'</option>').join('');$('inspect-layer').value=oldLayer;$('inspect-query').innerHTML=result.trace.tokens.map((t,i)=>'<option value="'+i+'">'+i+' · '+escape(t)+'</option>').join('');$('inspect-query').value=oldQuery!==''&&Number(oldQuery)<result.trace.ids.length?oldQuery:String(result.trace.ids.length-1);}
function vectorMarkup(v){const max=Math.max(...v.map(Math.abs),.001);return v.map(n=>'<span class="vector-cell" style="background:'+(n>=0?'rgba(63,157,124,':'rgba(75,116,181,')+(.12+.55*Math.abs(n)/max)+')" title="'+n.toFixed(8)+'">'+n.toFixed(2)+'</span>').join('');}
function renderInternals(){if(!result)return;const layer=Number($('inspect-layer').value),head=Number($('inspect-head').value),position=Number($('inspect-query').value),values=C.blockInternals(MODEL,result.trace,layer,position,head),o=operations[operation];$('block-flow').innerHTML=Object.entries(operations).map(([key,x],i)=>'<button class="operation-node '+(key===operation?'active':'')+'" data-operation="'+key+'" aria-pressed="'+(key===operation)+'"><span>0'+(i+1)+'</span><strong>'+x[0]+'</strong><small>'+x[1]+'</small></button>').join('');$('operation-title').textContent=o[2];$('operation-description').textContent=o[3];$('operation-formula').textContent=o[4];$('operation-help').dataset.help=o[7];$('vector-a-label').textContent=o[5]+' · '+values[o[5]].length+' numbers';$('vector-b-label').textContent=o[6]+' · '+values[o[6]].length+' numbers';$('vector-a').innerHTML=vectorMarkup(values[o[5]]);$('vector-b').innerHTML=vectorMarkup(values[o[6]]);$('attention-detail').textContent='Block '+(layer+1)+', head '+(head+1)+', query “'+result.trace.tokens[position]+'” at position '+position+'. Scores are scaled dot products of this query with each key.';
 $('score-table').innerHTML='<div class="score-row header"><span>Key position</span><span>Score</span><span>Weight</span><span>%</span></div>'+result.trace.tokens.map((t,i)=>'<div class="score-row '+(i>position?'masked':'')+'"><span>'+i+' · '+escape(t)+'</span><span>'+(i>position?'−∞':values.scores[i].toFixed(2))+'</span><div class="candidate-track"><div class="candidate-fill" style="width:'+(i>position?0:values.attention[i]*100)+'%"></div></div><span>'+(i>position?'mask':(values.attention[i]*100).toFixed(1))+'</span></div>').join('');}
function renderTensor(){const name=tensorName,info=C.tensorInfo(name,MODEL),v=MODEL.weights[name],matrix=info.shape.length===2?v:[v],rows=matrix.length,cols=matrix[0].length;$('tensor-select').value=name;$('tensor-shape').textContent=info.shape.join(' × ')+' · '+info.count.toLocaleString()+' parameters';$('tensor-description').textContent=info.description;$('tensor-operation').textContent=info.operation;$('tensor-row').max=rows-1;$('tensor-col').max=cols-1;let row=Math.min(rows-1,Math.max(0,Number($('tensor-row').value)||0)),col=Math.min(cols-1,Math.max(0,Number($('tensor-col').value)||0));row=Math.floor(row);col=Math.floor(col);$('tensor-row').value=row;$('tensor-col').value=col;$('scalar-value').textContent=matrix[row][col].toFixed(8);tensorStart=Math.floor(row/16)*16;$('tensor-window-label').textContent='Rows '+tensorStart+'–'+Math.min(rows-1,tensorStart+15)+' · '+cols+' columns';$('tensor-grid').style.setProperty('--cols',cols);const max=Math.max(...matrix.flat().map(Math.abs),.001);$('tensor-grid').innerHTML=matrix.slice(tensorStart,tensorStart+16).map((r,ri)=>r.map((n,ci)=>'<button class="tensor-cell '+(row===tensorStart+ri&&col===ci?'selected':'')+'" data-tensor-row="'+(tensorStart+ri)+'" data-tensor-col="'+ci+'" aria-label="Row '+(tensorStart+ri)+', column '+ci+': '+n.toFixed(8)+'" style="background:'+(n>=0?'rgba(121,235,202,':'rgba(140,189,255,')+(.12+.88*Math.abs(n)/max)+')"></button>').join('')).join('');$('tensor-prev').disabled=tensorStart===0;$('tensor-next').disabled=tensorStart+16>=rows;}
const architecture=[['Transformer blocks','5','Each block has distinct trained weights.','layers'],['Hidden width','32','Numbers in each residual-stream vector.','width'],['Attention heads','4','Independent query/key/value subspaces.','heads'],['Head dimension','8','32 dimensions split into four heads.','headWidth'],['MLP hidden width','64','Expansion before GELU and projection.','ffWidth'],['Vocabulary size','55','Names, words, and special tokens.','tokenizer'],['Context positions','64','Learned position-embedding rows.','position'],['Learned scalars','48,352','65 inspectable parameter tensors.','parameterCount'],['Norm epsilon','1e-5','Stability term inside normalization.','epsilon'],['Activation','GELU','Tanh approximation in the MLP.','mlp'],['Output head','55 × 32','One score per vocabulary token.','outputHead'],['Precision','FP32 → JS','Float32 training; JS Number inference.','precision']];
const training=[['Batch size','96','Examples per optimizer update.','batch'],['Optimizer steps','900','Updates to the learned parameters.','steps'],['Learning rate','0.003 → 0.0003','Cosine decay across the training run.','learningRate'],['Optimizer','AdamW','β₁ 0.9 · β₂ 0.999 · ε 1e-8.','optimizer'],['Weight decay','0.01','Decoupled parameter shrinkage.','weightDecay'],['Gradient norm cap','1.0','Rescale oversized training gradients.','clip'],['Training seed','20260915','Initialization and data sampling seeds.','trainingSeed'],['Objective','Cross entropy','Name and <eos> next-token targets.','loss']];
function parameterCards(rows){return rows.map(([title,value,copy,key])=>'<button class="parameter-card" data-help="'+key+'"><span class="parameter-title">'+title+'<span aria-hidden="true">ⓘ</span></span><strong>'+value+'</strong><small>'+copy+'</small></button>').join('');}
function renderTraining(){const logs=M.loss_history,i=Number($('training-step').value),current=logs[i];$('training-step').max=logs.length-1;$('loss-step').textContent=current.step;$('loss-value').textContent=current.loss.toFixed(4);const pts=logs.map(x=>[10+x.step/900*580,185-x.loss/4.1*170]);$('loss-chart').innerHTML='<title>Actual training cross entropy by optimizer step</title><path d="M10 10V185H590" fill="none" stroke="#466179" stroke-width="1"/><path d="M10 100H590" fill="none" stroke="#263c50" stroke-width="1"/><polyline points="'+pts.map(x=>x.join(',')).join(' ')+'" fill="none" stroke="#79ebca" stroke-width="3"/><circle cx="'+pts[i][0]+'" cy="'+pts[i][1]+'" r="6" fill="#79ebca" stroke="#e9fff7" stroke-width="2"/>';$('architecture-parameters').innerHTML=parameterCards(architecture);$('training-parameters').innerHTML=parameterCards(training);}
const stackNodes={
 browser:{client:['YOUR DEVICE','Browser UI','Context + controls','The browser receives the static page and embedded checkpoint. It holds the editable prompt and displays the visual inspector.','index.html · self-contained application'],edge:['HOSTING','HTTPS + public access','Sites edge','Sites serves this public deployment. Access control is outside this demo’s numerical model and does not contribute to its predictions.','Public Sites URL → document response'],runtime:['EXECUTION','Browser JavaScript','CPU inference','The page runs the trained model locally. No prediction request leaves the browser in the Playground; the checkpoint and engine are already embedded.','EngineeringCore.generate(MODEL, request)'],memory:['REQUEST STATE','Context + KV cache','Temporary arrays','A fresh model instance owns the current run’s vectors. Weights are read-only; caches and activations are recreated for new runs.','5 × positions × 2 × 32 cached scalars']},
 server:{client:['YOUR DEVICE','Browser client','POST JSON','Click Send request to transmit the current context and settings to the same-origin prediction API. The UI measures the complete round trip.','POST /api/predict'],edge:['API BOUNDARY','Validate request','Method + shape + limits','The server checks JSON content type, request size, context length, setting ranges, and same-origin browser requests before running the model.','settings(request.settings) · 64-position limit'],runtime:['SERVER EXECUTION','Worker + checkpoint','CPU inference','The deployed JavaScript Worker runs the same model engine and checkpoint. Each request gets its own model instance; no external model provider is called.','EngineeringCore.generate(MODEL, body)'],memory:['RESPONSE','Tokens + measurements','JSON result','The response contains generated tokens, processed probabilities, stop reason, phase timings, and computation counts. The server does not persist the prompt.','text · generated · timings · usage']}
};
function renderDeployment(){const nodes=stackNodes[stackMode];document.querySelectorAll('[data-stack]').forEach(b=>{b.classList.toggle('active',b.dataset.stack===stackMode);b.setAttribute('aria-pressed',String(b.dataset.stack===stackMode))});$('stack-lanes').innerHTML='<div class="stack-lane"><div class="lane-label">'+(stackMode==='browser'?'DELIVERY + LOCAL RUN':'REQUEST + RESPONSE')+'</div><div class="lane-nodes">'+Object.entries(nodes).map(([key,x])=>'<button class="stack-node '+(key===stackSelected?'active':'')+'" data-stack-node="'+key+'" aria-pressed="'+(key===stackSelected)+'"><small>'+x[0]+'</small><strong>'+x[1]+'</strong><span>'+x[2]+'</span></button>').join('')+'</div></div>';const x=nodes[stackSelected];$('stack-detail').innerHTML='<div><h3>'+x[1]+'</h3><code>'+escape(x[4])+'</code></div><p>'+x[3]+'</p>';$('api-request').textContent=JSON.stringify(currentRequest(),null,2);if(location.protocol==='file:'){$('api-send').disabled=true;$('api-runtime').textContent='Open the hosted or local-server URL to call the API.';}else $('api-send').disabled=apiBusy;}
async function sendAPI(){if(apiBusy)return;apiBusy=true;stackMode='server';stackSelected='runtime';renderDeployment();$('api-status').textContent='RUNNING';$('api-result').textContent='Request in flight…';const start=performance.now();try{const response=await fetch('/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(currentRequest())});const data=await response.json();$('api-response').textContent=JSON.stringify(data,null,2);if(!response.ok)throw Error(data.error||'HTTP '+response.status);const roundTrip=performance.now()-start;$('api-status').textContent='HTTP '+response.status;$('api-result').innerHTML='<strong>'+escape(data.text||'<eos>')+'</strong><br>'+data.generated.map(x=>escape(x.token)).join(' → ')+'<br><span class="small">'+roundTrip.toFixed(1)+' ms round trip · '+data.timings.totalMs.toFixed(2)+' ms server computation<br>'+data.usage.layerPositionEvaluations+' block-position evaluations · stop: '+data.stop+'</span>';}catch(e){$('api-status').textContent='REQUEST FAILED';$('api-result').textContent=e.message+' Open the deployed site or run node dev-server.mjs for the real API.';}finally{apiBusy=false;renderDeployment();}}
function showHelp(key){const x=help[key];if(!x)return;$('help-title').textContent=x[0];$('help-type').textContent=x[1];$('help-description').textContent=x[2];$('help-example').textContent=x[3];$('help-effect').textContent=x[4];if(!$('help-dialog').open)$('help-dialog').showModal();}
function setView(view){stopTrace();activeView=view;document.querySelector('.app').dataset.activeView=view;$('reference-note').hidden=view==='studio';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view===view)));for(const v of ['studio','playground','internals','training','deployment'])$('view-'+v).hidden=v!==view;if(view==='internals')renderInternals();if(view==='deployment')renderDeployment();}
document.addEventListener('click',e=>{const h=e.target.closest('[data-help]');if(h){showHelp(h.dataset.help);return;}const l=e.target.closest('[data-layer]');if(l){stopTrace();selectedLayer=Number(l.dataset.layer);traceStage=selectedLayer+1;renderPlayground();return;}const op=e.target.closest('[data-operation]');if(op){operation=op.dataset.operation;renderInternals();return;}const cell=e.target.closest('[data-tensor-row]');if(cell){$('tensor-row').value=cell.dataset.tensorRow;$('tensor-col').value=cell.dataset.tensorCol;renderTensor();return;}const node=e.target.closest('[data-stack-node]');if(node){stackSelected=node.dataset.stackNode;renderDeployment();}});
$('help-close').onclick=()=>$('help-dialog').close();$('help-dialog').addEventListener('click',e=>{if(e.target===$('help-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
let editTimer;$('context').oninput=()=>{clearTimeout(editTimer);editTimer=setTimeout(compute,180)};
for(const id of ['mode','temperature','top-k','top-p','max-tokens','seed','cache-toggle'])$(id).addEventListener(id==='mode'||id==='cache-toggle'?'change':'input',compute);
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{clearTimeout(editTimer);$('context').value=b.dataset.preset==='swap'?'My dog is named Luna. My cat is named Milo.':b.dataset.preset==='missing'?'My cat is named Luna.':'My dog is named Milo. My cat is named Luna.';compute()});$('run').onclick=compute;$('play-trace').onclick=playTrace;$('step-trace').onclick=()=>{stopTrace();traceStage=(traceStage+1)%7;selectedLayer=Math.min(4,Math.max(0,traceStage-1));renderPlayground()};$('play-head').onchange=renderPlayground;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('jump-internals').onclick=()=>{setView('internals');$('tensor-select').focus()};
for(const id of ['inspect-layer','inspect-head','inspect-query'])$(id).onchange=renderInternals;
$('tensor-select').innerHTML=Object.keys(MODEL.weights).map(name=>{const i=C.tensorInfo(name,MODEL);return'<option value="'+name+'">'+name+' ['+i.shape.join('×')+']</option>'}).join('');$('tensor-select').onchange=()=>{tensorName=$('tensor-select').value;$('tensor-row').value=0;$('tensor-col').value=0;renderTensor()};$('tensor-row').oninput=renderTensor;$('tensor-col').oninput=renderTensor;$('tensor-prev').onclick=()=>{$('tensor-row').value=Math.max(0,tensorStart-16);renderTensor()};$('tensor-next').onclick=()=>{$('tensor-row').value=tensorStart+16;renderTensor()};$('training-step').oninput=renderTraining;
document.querySelectorAll('[data-stack]').forEach(b=>b.onclick=()=>{stackMode=b.dataset.stack;renderDeployment()});$('api-send').onclick=sendAPI;
$('download-checkpoint').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(MODEL)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='name-recall-5l-checkpoint.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('present').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{$('present').textContent='Use browser full screen'}};document.addEventListener('fullscreenchange',()=>$('present').textContent=document.fullscreenElement?'Exit presentation ↙':'Present ↗');document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTrace()});
document.querySelector('[role="tablist"]').addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('[data-view]')],i=tabs.indexOf(e.target);if(i<0)return;let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;else if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=tabs.length-1;else return;e.preventDefault();setView(tabs[n].dataset.view);tabs[n].focus()});
compute();
// Optional, page-scoped agent access to the same local prediction action.
const modelContext=document.modelContext;
if(modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tool={name:'run_name_prediction',title:'Run name prediction',description:'Set the Playground context and decoding settings, run the local trained model, and display its prediction and inspection trace. No network request is made.',inputSchema:{type:'object',properties:{context:{type:'string',maxLength:4096},settings:{type:'object',properties:{temperature:{type:'number',minimum:0,maximum:2},topK:{type:'integer',minimum:0,maximum:55},topP:{type:'number',minimum:.05,maximum:1},maxTokens:{type:'integer',minimum:1,maximum:8},seed:{type:'integer',minimum:0,maximum:4294967295},mode:{type:'string',enum:['greedy','sample']},useCache:{type:'boolean'}},additionalProperties:false}},required:['context'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){
  if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['context','settings'].includes(k)))throw Error('Supply a context string and optional settings.');
  if(input.settings&&Object.keys(input.settings).some(k=>!Object.keys(C.DEFAULTS).includes(k)))throw Error('Unknown decoding setting.');
  const checked=C.generate(MODEL,input); // Validate before changing visible state.
  clearTimeout(editTimer);$('context').value=input.context;
  const s=checked.settings;for(const [id,key] of [['temperature','temperature'],['top-k','topK'],['top-p','topP'],['max-tokens','maxTokens'],['seed','seed'],['mode','mode']])$(id).value=s[key];$('cache-toggle').checked=s.useCache;
  compute();setView('playground');
  return{text:result.text,generated:result.generated,stop:result.stop,usage:result.usage,settings:result.settings};
 }};
 try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
window.engineeringLab={snapshot:()=>({view:activeView,result,selectedLayer,operation,tensorName,traceStage,playing}),helpKeys:Object.keys(help),core:C,payload:MODEL};
})();
