(()=>{
'use strict';
const $=id=>document.getElementById(id),C=EngineeringCore,E=DogModelEngine,T=TrainingEngine;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const artifacts=[
 ['dataset','D','Dataset','44 examples + 16 held out','fixed','The training pairs teach the model what to predict. Evaluation prompts are separate wording/order combinations and are never used for updates.'],
 ['tokenizer','T','Tokenizer','55 token IDs','fixed','The tokenizer maps text to integer IDs. Its vocabulary stays fixed when the model is reset or trained.'],
 ['config','C','Architecture','5 blocks · 32 dimensions','fixed','This configuration defines tensor shapes and operations. Training changes the values inside those shapes.'],
 ['weights','W','Weights','65 learned tensors','live','These are the live model’s current learned values. Reset reinitializes matrices with small random values, normalization scales with 1, and biases with 0.'],
 ['optimizer','O','Optimizer + gradients','AdamW training state','live','Gradients describe the last batch’s learning signal. AdamW keeps first and second moments to scale future updates. Inference does not use this state.'],
 ['log','L','Training log','Loss, gradients, updates','live','Every row is measured during an actual optimizer step. Batch loss is measured before that row’s weight update.'],
 ['evaluation','E','Evaluation','16 separate prompts','live','These prompts are excluded from the training sampler. This small test measures this classroom lesson, not general language ability.'],
 ['checkpoint','K','Checkpoint','Portable model snapshot','live','A checkpoint packages the architecture, vocabulary, and model weights. It is enough for inference; exact training continuation additionally needs optimizer and sampler state.'],
 ['inference','→','Inference trace','Tokens, layers, scores','temporary','This trace is created by the latest forward pass shown on the right. It records actual activations, attention, logits, and decoded tokens.'],
 ['cache','V','KV cache','Temporary request memory','temporary','Each of the five attention blocks stores keys and values for this input. This cache is rebuilt for another checkpoint or prompt and is not learned model data.']
];
const help={lr:['Peak learning rate','How large each AdamW weight update can be. The tested default is 0.003. During each multi-step run, a cosine schedule smoothly lowers it to 0.0003 (10% of the peak). One-step mode uses the full selected rate. Larger rates can make learning unstable. Inference temperature is independent.'],batch:['Batch size','The model averages gradients from this many sampled examples before updating its weights. A batch of 16 is small enough for an interactive CPU demo. Sampling is with replacement.'],steps:['Optimizer steps','How many additional updates to run when you press Train. One step includes a batch forward pass, loss calculation, backpropagation, and one AdamW update. Pause preserves the current weights and optimizer. Press Train again to run the selected number of additional updates with a new learning-rate schedule.'],seed:['Reset seed','Reset creates reproducible random initial weights and a reproducible training-example sampler. The same seed and training settings reproduce the numerical learning run. Reset also clears optimizer moments and logs.'],backprop:['What backpropagation does','The loss sends gradients backward through the output head, all five blocks, and the embeddings. AdamW then updates the learned parameters. The orange block bars show measured RMS changes in their weights. Normalization epsilon is 1e-5; gradient norm is capped at 1; weight decay is 0.01.'],inference:['What inference does','The right side takes a read-only snapshot of the selected checkpoint. It tokenizes your context, runs five blocks, and chooses the highest-scoring next token. Temperature is 1, top-k is off, top-p is 1, and the output limit is 4. The Playground tab has adjustable decoding controls for the original trained example.']};
let worker=null,generation=0,live=null,frozen=null,useFrozen=false,inference=null,inferenceVersion=null,inferenceSource=null,baseline=null,mode='random',opened=null,artifactTensor=null,optimizerPending=false,inputTimer,workerUrl;
function label(step=live?.step||0){return(mode==='pretrained'?'Trained example + ':'Live run · ')+step+' updates';}
function post(type,extra={}){if(worker)worker.postMessage({type,generation,...extra});}
function controls(){const ready=!!live,busy=!!live?.running;for(const id of ['studio-train','studio-one','studio-freeze','studio-predict'])$(id).disabled=!ready;for(const id of ['studio-lr','studio-batch','studio-steps'])$(id).disabled=busy;$('studio-one').disabled=!ready||busy;$('studio-train').textContent=busy?'Ⅱ Pause training':'▶ Train model';$('studio-compare').disabled=!frozen;$('studio-compare').textContent=useFrozen?'Return to live inference':'Use frozen for inference';}
function initialize(randomize=true){const seed=Number($('studio-seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295){$('studio-message').textContent='Reset seed must be an integer from 0 to 4294967295.';return;}generation++;live=null;frozen=null;useFrozen=false;inference=null;mode=randomize?'random':'pretrained';baseline=null;optimizerPending=false;$('studio-status').textContent='INITIALIZING';$('studio-message').textContent=randomize?'Resetting weights, optimizer state, and the training log…':'Loading the original trained example with a fresh optimizer…';controls();post('initialize',{payload:MODEL,seed,randomize});}
function run(steps){if(!live)return;if(live.running){post('pause');return;}post('train',{steps,options:{learningRate:Number($('studio-lr').value),batchSize:Number($('studio-batch').value)}});}
function render(){if(!live)return;const last=live.last;$('studio-status').textContent=live.running?'TRAINING':live.step?'PAUSED / READY':mode==='pretrained'?'EXAMPLE LOADED':'UNTRAINED';$('studio-artifact-step').textContent='Step '+live.step;$('studio-step').textContent=live.step;$('studio-loss').textContent=last?last.loss.toFixed(4):'—';$('studio-gradient').textContent=last?last.gradientNorm.toFixed(3):'—';$('studio-cycle-loss').textContent=last?last.loss.toFixed(3):'Compare';$('studio-example').textContent=last?.example.context||'My dog is named Milo.';$('studio-target').textContent=(last?.example.target||'Milo')+' → <eos>';
 const max=Math.max(...(last?.blockUpdates||[0]),1e-9);$('studio-training-blocks').innerHTML=Array.from({length:5},(_,i)=>'<button class="training-block '+(live.running?'updating':'')+'" data-artifact="weights"><span>BLOCK '+(i+1)+'</span><div><i style="width:'+(last?Math.max(2,last.blockUpdates[i]/max*100):0)+'%"></i></div><small>Δ '+(last?last.blockUpdates[i].toExponential(1):'0.0')+'</small></button>').join('');
 $('studio-message').textContent=live.running?'Learning from batches of '+(last?.batchSize||Number($('studio-batch').value))+' examples · '+live.remaining+' updates remaining · LR '+(last?.learningRate||Number($('studio-lr').value)).toFixed(5)+'.':live.step?'Training paused at step '+live.step+'. Continue training, freeze this checkpoint, or reset and start again.':mode==='pretrained'?'Original trained weights loaded. You can run inference immediately or continue training on this lesson.':'Weights are random. The next-token guess has not learned this lesson yet.';
 const logs=live.history,maxLoss=Math.max(4,...logs.map(x=>x.loss)),end=Math.max(50,live.step),points=logs.map(x=>(8+x.step/end*464)+','+(112-x.loss/maxLoss*100)).join(' ');$('studio-loss-chart').innerHTML='<title>Measured batch loss across '+live.step+' optimizer steps</title><path d="M8 8V112H472M8 60H472" fill="none" stroke="#304252"/><text x="12" y="20" fill="#a6b8cc" font-size="12">'+maxLoss.toFixed(1)+'</text>'+(logs.length?'<polyline points="'+points+'" fill="none" stroke="#ffca8a" stroke-width="2.5"/>':'<text x="140" y="68" fill="#a6b8cc" font-size="14">Train to draw a learning curve</text>')+'<text x="8" y="125" fill="#a6b8cc" font-size="12">0</text><text x="430" y="125" fill="#a6b8cc" font-size="12">'+end+'</text>';
 $('studio-weight-version').textContent='48,352 parameters · latest step '+live.step;$('studio-bridge-note').textContent=useFrozen?'Inference is pinned to the frozen checkpoint at step '+frozen.step+'.':$('studio-auto').checked?'Updated every 5 training steps.':'Automatic inference is off. Click Run inference for the latest weights.';
 if(live.evaluation){$('studio-eval-score').textContent=live.evaluation.correct+' / '+live.evaluation.total;$('studio-eval-step').textContent='Live weights · evaluated at step '+live.evaluation.step;}
 controls();
}
function predict(){if(!live)return;const selected=useFrozen?frozen:live;try{inference=C.generate(selected.payload,{context:$('studio-context').value,settings:{maxTokens:4}});inferenceVersion=selected.step;inferenceSource=useFrozen?'Frozen':mode==='pretrained'?'Trained example':'Live';const p=inference.probabilities.raw,rank=p.map((v,id)=>({v,id})).sort((a,b)=>b.v-a.v).slice(0,4);$('studio-answer').textContent=inference.generated[0].token;$('studio-confidence').textContent=(inference.generated[0].probability*100).toFixed(1)+'%';$('studio-tokens').textContent=inference.generated.map(x=>x.token).join(' → ')+' · stop: '+inference.stop;$('studio-checkpoint-label').textContent=inferenceSource.toUpperCase()+' · STEP '+inferenceVersion;
 $('studio-candidates').innerHTML=rank.map(x=>'<div class="candidate-row"><span>'+esc(selected.payload.metadata.vocab[x.id])+'</span><div class="candidate-track"><div class="candidate-fill" style="width:'+x.v*100+'%"></div></div><span class="percent">'+(x.v*100).toFixed(1)+'%</span></div>').join('');
 $('studio-forward-path').innerHTML='<span class="forward-input">'+inference.usage.inputTokens+' tokens</span>'+inference.trace.readouts.map((logits,l)=>{const q=E.softmax(logits),id=q.indexOf(Math.max(...q));return'<button data-artifact="inference" title="Intermediate readout: '+esc(selected.payload.metadata.vocab[id])+' · '+(q[id]*100).toFixed(1)+'%"><small>BLOCK</small><strong>'+(l+1)+'</strong></button>'}).join('')+'<span class="forward-input">55 scores</span>';
 }catch(error){inference=null;$('studio-answer').textContent='Check input';$('studio-confidence').textContent='—';$('studio-tokens').textContent=error.message;$('studio-candidates').replaceChildren();$('studio-forward-path').replaceChildren();}}
function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function table(headers,rows){return'<div class="artifact-table-wrap"><table class="artifact-table"><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function summaryGrid(rows){return'<div class="artifact-summary">'+rows.map(([a,b])=>'<div><span>'+esc(a)+'</span><strong>'+esc(b)+'</strong></div>').join('')+'</div>';}
function openHelp(key){const h=help[key];if(!h)return;opened=null;$('artifact-title').textContent=h[0];$('artifact-category').textContent='PARAMETER GUIDE';$('artifact-explanation').textContent=h[1];$('artifact-revision').textContent='Training studio';$('artifact-download').hidden=true;$('artifact-content').replaceChildren();$('studio-artifact-dialog').showModal();}
function openArtifact(key,valueOverride){if(!live)return;const info=artifacts.find(a=>a[0]===key);if(!info)return;let value;
 if(key==='optimizer'&&!valueOverride){optimizerPending=true;post('optimizer');$('studio-message').textContent='Reading the optimizer’s current state…';return;}
 if(key==='dataset')value=T.lesson(MODEL.metadata.vocab);
 else if(key==='tokenizer')value={rules:'Normalize curly apostrophe; split words, punctuation and special tokens; unknown pieces map to <unk>.',specialTokens:['<pad>','<bos>','<eos>','<answer>','<unk>'],vocabulary:MODEL.metadata.vocab.map((token,id)=>({id,token}))};
 else if(key==='config')value={...MODEL.metadata.config,vocabularySize:55,parameters:48352,activation:'GELU tanh approximation',positionEncoding:'Learned absolute embeddings',learningRateSchedule:'Each multi-step run: peak × [0.1 + 0.9 × (1 + cos(π × progress)) / 2]; one-step mode uses peak.',optimizer:{name:'AdamW',beta1:.9,beta2:.999,epsilon:1e-8,weightDecay:.01,gradientClip:1},initialization:{seed:live.payload.metadata.seed,matrixStd:.02,normScale:1,bias:0}};
 else if(key==='weights')value=live.payload.weights;
 else if(key==='optimizer')value=valueOverride;
 else if(key==='log')value=live.history;
 else if(key==='evaluation')value=live.evaluation;
 else if(key==='checkpoint')value=useFrozen?frozen.payload:live.payload;
 else if(key==='inference')value=inference?{checkpoint:{source:inferenceSource,step:inferenceVersion},...inference}:{message:'Run inference to create a trace.'};
 else if(key==='cache')value=inference?{checkpoint:{source:inferenceSource,step:inferenceVersion},positions:inference.trace.ids.length,scope:'Input prefill cache; generation may append more positions.',layers:inference.trace.cache.map((c,i)=>({block:i+1,keys:c.k,values:c.v}))}:{message:'Run inference to create a KV cache.'};
 const revision=key==='inference'||key==='cache'?inferenceVersion:key==='evaluation'?live.evaluation?.step:key==='checkpoint'&&useFrozen?frozen.step:key==='optimizer'?value.step:live.step;
 opened={key,value:structuredClone(value),step:revision};artifactTensor=null;$('artifact-title').textContent=info[2];$('artifact-category').textContent=info[4]==='fixed'?'FIXED ARTIFACT':info[4]==='live'?'TRAINING ARTIFACT':'INFERENCE ARTIFACT';$('artifact-explanation').textContent=info[5];$('artifact-revision').textContent=info[4]==='fixed'?'Fixed for this lesson':'Snapshot at step '+revision+' · reopen to refresh';$('artifact-download').hidden=false;renderArtifact();if(!$('studio-artifact-dialog').open)$('studio-artifact-dialog').showModal();}
function renderArtifact(){const {key,value}=opened,el=$('artifact-content');
 if(key==='dataset'){el.innerHTML=summaryGrid([['Training examples',value.train.length],['Evaluation examples',value.test.length],['Names',value.names.join(', ')]])+'<h3>Training pairs</h3>'+table(['Context','Target'],value.train.map(x=>[x.context,x.target+' → <eos>']))+'<h3>Held-out evaluation</h3>'+table(['Context','Target'],value.test.map(x=>[x.context,x.target]));}
 else if(key==='tokenizer'){el.innerHTML='<div class="vocabulary-grid">'+value.vocabulary.map(x=>'<span><small>'+x.id+'</small>'+esc(x.token)+'</span>').join('')+'</div><p class="body-copy">'+esc(value.rules)+'</p>';}
 else if(key==='weights'||key==='optimizer'){const tensors=key==='weights'?value:value.tensors;artifactTensor=artifactTensor||Object.keys(tensors)[0];el.innerHTML=(key==='optimizer'?summaryGrid([['Update step',value.step],['β₁ / β₂',value.beta1+' / '+value.beta2],['Gradient clip',value.gradientClip]]):'')+'<label class="field-label">Choose any tensor<select id="artifact-tensor-select">'+Object.keys(tensors).map(name=>'<option '+(name===artifactTensor?'selected':'')+'>'+esc(name)+'</option>').join('')+'</select></label><div id="artifact-tensor-body"></div>';$('artifact-tensor-select').onchange=()=>{artifactTensor=$('artifact-tensor-select').value;renderArtifactTensor()};renderArtifactTensor();}
 else if(key==='log'){el.innerHTML=value.length?table(['Step','Batch loss','Gradient norm','Clip scale','Update norm','ms'],value.map(x=>[x.step,x.loss.toFixed(5),x.gradientNorm.toFixed(4),x.clipScale.toFixed(3),x.updateNorm.toFixed(5),x.ms.toFixed(1)])):'<div class="artifact-empty">No optimizer steps yet. Train one batch to create a real log entry.</div>';}
 else if(key==='evaluation'){el.innerHTML=summaryGrid([['Correct',value.correct+' / '+value.total],['Checkpoint step',value.step]])+table(['Prompt','Target','Prediction','Result'],value.rows.map(x=>[x.context,x.target,x.prediction,x.correct?'Correct':'Miss']));}
 else if(key==='checkpoint'){el.innerHTML=summaryGrid([['Source',value.metadata.provenance],['Live updates',value.metadata.steps],['Parameters',value.metadata.parameters],['Tensors',Object.keys(value.weights).length]])+'<p class="body-copy">Download this artifact to keep this checkpoint after closing the page. It contains every learned scalar, vocabulary entry, and architecture setting.</p><pre class="artifact-code">'+esc(JSON.stringify(value.metadata,null,2))+'</pre>';}
 else if(key==='inference'&&value.trace){el.innerHTML=summaryGrid([['Prediction',value.text],['Input tokens',value.usage.inputTokens],['Checkpoint',value.checkpoint.source+' · '+value.checkpoint.step]])+table(['Block','Top intermediate token','Readout probability'],value.trace.readouts.map((x,i)=>{const p=E.softmax(x),id=p.indexOf(Math.max(...p));return[i+1,MODEL.metadata.vocab[id],(p[id]*100).toFixed(2)+'%']}))+'<p class="body-copy">Only block 5 gives the trained final readout. The download includes all token vectors, attention heads, scores, and generated tokens.</p><pre class="artifact-code">'+esc(JSON.stringify({tokens:value.trace.tokens,tokenIds:value.trace.ids,logits:value.trace.initialLogits,generated:value.generated},null,2))+'</pre>';}
 else if(key==='cache'&&value.layers){el.innerHTML=summaryGrid([['Prefill positions',value.positions],['Layers',5],['K + V scalars',value.positions*5*64]])+'<p class="body-copy">'+esc(value.scope)+'</p>'+value.layers.map(x=>'<details class="artifact-details"><summary>Block '+x.block+' · keys & values</summary><pre class="artifact-code">'+esc(JSON.stringify(x,null,2))+'</pre></details>').join('');}
 else el.innerHTML='<pre class="artifact-code">'+esc(JSON.stringify(value,null,2))+'</pre>';
}
function renderArtifactTensor(){const {key,value}=opened,payload={weights:key==='weights'?value:live.payload.weights},info=C.tensorInfo(artifactTensor,payload),data=key==='weights'?value[artifactTensor]:value.tensors[artifactTensor],flat=key==='weights'?data.flat():data.gradient;const colorScale=Math.max(1e-20,...flat.map(Math.abs)),n=flat.length,rms=Math.sqrt(flat.reduce((s,v)=>s+v*v,0)/n);$('artifact-tensor-body').innerHTML=summaryGrid([['Shape',info.shape.join(' × ')],['Scalars',n],['RMS '+(key==='weights'?'weight':'gradient'),rms.toExponential(3)]])+'<p class="body-copy">'+esc(info.description)+'</p><p class="small muted">Color shows sign and relative magnitude. Click a cell to read its exact value.</p><div class="artifact-heatmap" style="--tensor-cols:'+info.shape.at(-1)+'">'+flat.map((v,i)=>'<button class="artifact-scalar-cell" data-scalar-index="'+i+'" title="Index '+i+': '+v+'" aria-label="Parameter '+i+': '+v+'" style="background:'+(v>=0?'rgba(255,202,138,':'rgba(140,189,255,')+(.12+.88*Math.abs(v)/colorScale)+')"></button>').join('')+'</div><p class="artifact-scalar-readout" id="artifact-scalar-readout">Select a cell above.</p><details class="artifact-details"><summary>Full precision JSON</summary><pre class="artifact-code">'+esc(JSON.stringify(data,null,2))+'</pre></details>';
 $('artifact-tensor-body').onclick=e=>{const cell=e.target.closest('[data-scalar-index]');if(cell){const i=Number(cell.dataset.scalarIndex),cols=info.shape.at(-1);$('artifact-scalar-readout').textContent=artifactTensor+' ['+(info.shape.length===1?i:Math.floor(i/cols)+', '+i%cols)+'] = '+flat[i].toPrecision(12);}};}
$('studio-artifacts').innerHTML=artifacts.map(([key,icon,title,subtitle,type])=>'<button class="artifact-item" data-artifact="'+key+'"><span class="artifact-file-icon '+type+'">'+icon+'</span><span><strong>'+title+'</strong><small>'+subtitle+'</small></span><span class="artifact-chevron">›</span></button>').join('');
document.addEventListener('click',e=>{const a=e.target.closest('[data-artifact]');if(a){openArtifact(a.dataset.artifact);return;}const h=e.target.closest('[data-studio-help]');if(h)openHelp(h.dataset.studioHelp);});
$('artifact-close').onclick=()=>$('studio-artifact-dialog').close();$('artifact-download').onclick=()=>{if(opened)download(opened.value,'model-'+opened.key+'-step-'+opened.step+'.json')};
$('studio-train').onclick=()=>run(Number($('studio-steps').value));$('studio-one').onclick=()=>run(1);$('studio-reset').onclick=()=>initialize(true);$('studio-load').onclick=()=>initialize(false);$('studio-predict').onclick=predict;$('studio-auto').onchange=()=>{if($('studio-auto').checked)predict();render()};$('studio-context').oninput=()=>{clearTimeout(inputTimer);inputTimer=setTimeout(predict,180)};
document.querySelectorAll('[data-studio-preset]').forEach(b=>b.onclick=()=>{$('studio-context').value=b.dataset.studioPreset==='swap'?'My dog is named Luna. My cat is named Milo.':b.dataset.studioPreset==='missing'?'My cat is named Luna.':'My dog is named Milo. My cat is named Luna.';predict()});
$('studio-freeze').onclick=()=>{if(!live)return;frozen={step:live.step,payload:structuredClone(live.payload)};$('studio-message').textContent='Frozen checkpoint at step '+frozen.step+'. You can pin inference to it while the live model continues learning.';controls();};$('studio-compare').onclick=()=>{if(!frozen)return;useFrozen=!useFrozen;render();predict()};
try{workerUrl=URL.createObjectURL(new Blob([TRAINING_WORKER_SOURCE],{type:'text/javascript'}));worker=new Worker(workerUrl);worker.onmessage=({data:m})=>{if(m.generation!==generation)return;if(m.type==='error'){$('studio-message').textContent=m.message;return;}if(m.type==='optimizer'){if(optimizerPending){optimizerPending=false;openArtifact('optimizer',m.state);}return;}live=m;render();if(!inference||($('studio-auto').checked&&!useFrozen))predict();};worker.onerror=()=>{$('studio-message').textContent='The training worker could not start. Open the hosted lab in a browser with Web Worker support.';$('studio-status').textContent='WORKER ERROR';};initialize();}catch(error){$('studio-status').textContent='UNAVAILABLE';$('studio-message').textContent='Live training needs browser Web Workers. '+error.message;}
window.addEventListener('pagehide',()=>{worker?.terminate();if(workerUrl)URL.revokeObjectURL(workerUrl)},{once:true});
window.trainingStudio={snapshot:()=>({generation,live,frozen,useFrozen,inference,inferenceVersion,mode}),train:run,reset:()=>initialize(true),pause:()=>post('pause'),openArtifact};
})();
